# Omakase Ruby styling for Rails.
inherit_gem:
 rubocop-rails-omakase: "rubocop.yml"

AllCops:
   Exclude:
     - "vendor/**/*"
     - "db/**/*"
     - "bin/*"
     - "node_modules/**/*"
     - "config/initializers/devise.rb"
     - "config/environments/*.rb"
     - "Gemfile"
     - "Rakefile"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"